[tool.flake8]
extend-ignore = ["E402", "E501", "W503", "W504"]
max-line-length = 140

[tool.pytest]
log_cli = 1
log_cli_level = "INFO"

[tool.ruff.lint]
ignore = ["E402", "E501"]
select = ["E", "F", "W"]
