# SPDX-FileCopyrightText: 2019-2025 Valéry Febvre
#
# SPDX-License-Identifier: GPL-3.0-or-later

SPDX-PackageDownloadLocation = "https://flathub.org/apps/info.febvre.Komikku"
SPDX-PackageName = "Komikku"
SPDX-PackageSupplier = "Valéry Febvre <vfebvre@easter-eggs.com>"
version = 1

[[annotations]]
path = [
	# Documentation that should match the surrounding code
	"CONTRIBUTING.md",
	"README.md",
	"flatpak/README.md",
	"tests/README.md",
]
SPDX-FileCopyrightText = "Contributors to Komikku"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
	# Translations files
	"po/*.po",
	"po/*.pot",
	"po/LINGUAS",
	"po/POTFILES.in",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors to Komikku"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
	# Metadata files
	"Komikku.doap",
    "screenshots/*",
	"data/*.in"
]
SPDX-FileCopyrightText = "Valéry Febvre <vfebvre@easter-eggs.com>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
	# Icon files
	"data/icons/*.svg",
	"data/icons/old/*.svg",
	"data/images/*.png",
	"data/images/old/*.png",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
	# Flatpak dependencies files (generated by `flatpak-pip-generator`)
	"flatpak/*.json"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
	# Files for development
	".editorconfig",
	".gitignore",
	".pre-commit-config.yaml",
	"pylintrc",
	"setup.cfg",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "GPL-3.0-or-later"
