name: Build binaries

on:
  push:
    branches: [main]

jobs:
  build-macos:
    runs-on: macos-14-large
    steps:
      - uses: actions/checkout@v4

      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Install pip dependencies
        run: |
          pip install pyinstaller pyGObject meson

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements-optional.txt

      - name: Install brew dependencies
        run: |
          bre update
          brew install gtk4 create-dmg

      - name: Build
        run: |
          meson setup build
          meson compile -C build
          ls -la

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-macos-14-intel
          path: dist/*
